name: Deploy Worker
on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js {{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if Flotiq API key is set
        run: [ -z "$GATSBY_FLOTIQ_API_KEY" ] && echo "Flotiq API Key is not set, using a starter one." && GATSBY_FLOTIQ_API_KEY="40accb088d028cb0779d8fc2ea7646e4" || true
      - run: npm install -g gatsby-cli
      - run: npm install -g flotiq-cli
      - run: flotiq import . ${{ secrets.GATSBY_FLOTIQ_API_KEY }}
      - run: yarn install
      - run: gatsby build
        env:
          GATSBY_FLOTIQ_API_KEY: ${{ secrets.GATSBY_FLOTIQ_API_KEY }}
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}